// Generated by scripts/generate-menu.mjs. Do not edit.
// Original selection bounds, not archive artwork or a running Melee engine.
export const menuSource = {"path":"melee/src/melee/mn/mncharsel.c","sha256":"7d8ab4fd55c5904bb05065a5b1e57b00693998d2446894d9b0b6a695d1cb77de"};
export const menuIcons = [
  {
    "id": 22,
    "left": -30,
    "right": -24.4,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 8,
    "left": -24.4,
    "right": -17.4,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 7,
    "left": -17.4,
    "right": -10.4,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 5,
    "left": -10.4,
    "right": -3.4,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 12,
    "left": -3.4,
    "right": 3.6,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 17,
    "left": 3.6,
    "right": 10.6,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 1,
    "left": 10.6,
    "right": 17.6,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 0,
    "left": 17.6,
    "right": 24.4,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 25,
    "left": 24.4,
    "right": 30.2,
    "top": 20,
    "bottom": 13
  },
  {
    "id": 20,
    "left": -30,
    "right": -24.4,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 2,
    "left": -24.4,
    "right": -17.4,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 11,
    "left": -17.4,
    "right": -10.4,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 14,
    "left": -10.4,
    "right": -3.4,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 4,
    "left": -3.4,
    "right": 3.6,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 16,
    "left": 3.6,
    "right": 10.6,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 18,
    "left": 10.6,
    "right": 17.6,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 6,
    "left": 17.6,
    "right": 24.4,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 21,
    "left": 24.4,
    "right": 30.2,
    "top": 13,
    "bottom": 6
  },
  {
    "id": 24,
    "left": -23.4,
    "right": -17.4,
    "top": 6,
    "bottom": -1
  },
  {
    "id": 13,
    "left": -17.4,
    "right": -10.4,
    "top": 6,
    "bottom": -1
  },
  {
    "id": 15,
    "left": -10.4,
    "right": -3.4,
    "top": 6,
    "bottom": -1
  },
  {
    "id": 10,
    "left": -3.4,
    "right": 3.6,
    "top": 6,
    "bottom": -1
  },
  {
    "id": 3,
    "left": 3.6,
    "right": 10.6,
    "top": 6,
    "bottom": -1
  },
  {
    "id": 9,
    "left": 10.6,
    "right": 17.6,
    "top": 6,
    "bottom": -1
  },
  {
    "id": 23,
    "left": 17.6,
    "right": 23.6,
    "top": 6,
    "bottom": -1
  }
];
