import {dirtyHostContract} from './dirty-host-contract.mjs';
const sha=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),v=>v.toString(16).padStart(2,'0')).join('');
// Deliberately pinned, not regenerated by the instrumenter. A changed core,
// glue or host closure requires a new write-coverage audit before it can run.
export async function loadDirtyCore(){
 for(const [file,expected]of Object.entries(dirtyHostContract)){const r=await fetch('./'+file);if(!r.ok||await sha(await r.arrayBuffer())!==expected)throw Error('Unaudited dirty host source '+file);}
 const manifest=await(await fetch('./dirty-core.json')).json();if(manifest.originalSha256!=='a5b0eb0bbc9851bce8bc022a1cdab173bae8f6d405b8b2b039dc1f164df3a234'||manifest.pageBytes!==4096||manifest.counts.stores!==110316||manifest.counts.copy!==169||manifest.counts.fill!==61)throw Error('Unaudited dirty core');
 const bytes=new Uint8Array(await(await fetch('./melee-dirty.wasm')).arrayBuffer());if(await sha(bytes)!==manifest.instrumentedSha256)throw Error('Dirty core integrity');return {bytes,manifest};
}
