import {dirtyHostContract} from './dirty-host-contract.mjs';
const sha=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),v=>v.toString(16).padStart(2,'0')).join('');
// Deliberately pinned, not regenerated by the instrumenter. A changed core,
// glue or host closure requires a new write-coverage audit before it can run.
export async function loadDirtyCore(){
 for(const [file,expected]of Object.entries(dirtyHostContract)){const r=await fetch('./'+file);if(!r.ok||await sha(await r.arrayBuffer())!==expected)throw Error('Unaudited dirty host source '+file);}
 const manifest=await(await fetch('./dirty-core.json')).json();if(manifest.originalSha256!=='f0c6a7257496d65621233648e00b6eb0956ea9ce2608c65e919428414c8f5ae2'||manifest.pageBytes!==4096||manifest.counts.stores!==110316||manifest.counts.copy!==169||manifest.counts.fill!==61||manifest.counts.tableMutations!==0)throw Error('Unaudited dirty core');
 const bytes=new Uint8Array(await(await fetch('./melee-dirty.wasm')).arrayBuffer());if(await sha(bytes)!==manifest.instrumentedSha256)throw Error('Dirty core integrity');return {bytes,manifest};
}

// Fan out audited native/host store marks before consuming the instrumentation
// bitmap. Each consumer owns its pending set; clearing one never loses another's
// history. Metadata is outside gameplay memory and is not checkpointed.
const dirtyHubs=new WeakMap();
function dirtyHub(runtime){
 const {dirty,module,instance,audit}=runtime;
 if(!audit.instrumentedSha256||!(dirty instanceof Uint8Array)||dirty.byteLength!==524288)throw Error('Unaudited dirty subscription');
 const size=module.HEAPU8.length,count=size/4096;
 let hub=dirtyHubs.get(dirty.buffer);
 if(hub&&(hub.module!==module||hub.size!==size))throw Error('Dirty bitmap runtime identity');
 if(!hub){hub={module,size,subscribers:new Map(),trackers:0,versions:new Float64Array(count),poll(first=0,last=count){
   if(module.HEAPU8.length!==size||module.HEAPU8.buffer!==instance.exports.memory.buffer)throw Error('Dirty subscription memory growth or stale view');
   if(!Number.isInteger(first)||!Number.isInteger(last)||first<0||last<first||last>count)throw Error('Dirty poll range');
   for(let i=first;i<last;i++)if(dirty[i]){if(hub.versions[i]>=Number.MAX_SAFE_INTEGER)throw Error('Dirty page version exhausted');hub.versions[i]++;for(const pending of hub.subscribers.values())pending[i]=1;dirty[i]=0;}
 }};dirtyHubs.set(dirty.buffer,hub);}
 return {hub,size,count,dirty,module};
}
export function subscribeDirtyPages(runtime,role){
 if(typeof role!=='string')throw Error('Unaudited dirty subscription');
 const {hub,count,dirty}=dirtyHub(runtime);
 if(hub.subscribers.has(role))throw Error('Dirty subscription already owned');
 const pending=new Uint8Array(count).fill(1);hub.subscribers.set(role,pending);let closed=false;
 const check=()=>{if(closed)throw Error('Dirty subscription disposed');};
 return {read(){check();hub.poll();return pending;},clear(){check();pending.fill(0);},dispose(){if(closed)return;closed=true;hub.subscribers.delete(role);if(!hub.subscribers.size&&!hub.trackers)dirtyHubs.delete(dirty.buffer);}};
}
export function createDirtyRangeTracker(runtime){
 const {hub,module,dirty}=dirtyHub(runtime);hub.trackers++;let closed=false;
 return {
  stamp(ranges){
   if(closed||!Array.isArray(ranges))throw Error('Dirty range tracker unavailable');
   const result=[];
   for(const bytes of ranges){
    if(!(bytes instanceof Uint8Array)||bytes.buffer!==module.HEAPU8.buffer||bytes.byteOffset<module.HEAPU8.byteOffset||bytes.byteOffset+bytes.byteLength>module.HEAPU8.byteOffset+module.HEAPU8.byteLength)throw Error('Dirty tracked range ownership');
    if(!bytes.byteLength)continue;const first=Math.floor((bytes.byteOffset-module.HEAPU8.byteOffset)/4096),last=Math.ceil((bytes.byteOffset-module.HEAPU8.byteOffset+bytes.byteLength)/4096);hub.poll(first,last);
    for(let page=first;page<last;page++)result.push(page,hub.versions[page]);
   }
   return result;
  },
  dispose(){if(closed)return;closed=true;hub.trackers--;if(!hub.subscribers.size&&!hub.trackers)dirtyHubs.delete(dirty.buffer);}
 };
}
