(module
 (import "env" "live" (memory $live 0 32768))
 (import "env" "pages" (memory $pages 0 32768))
 (func (export "equal") (param $a i32) (param $b i32) (result i32) (local $end i32)
  (local.set $end (i32.add (local.get $a) (i32.const 65536)))
  (loop $loop
   (if (v128.any_true (v128.xor (v128.load $live (local.get $a)) (v128.load $pages (local.get $b)))) (then (return (i32.const 0))))
   (local.set $a (i32.add (local.get $a) (i32.const 16)))
   (local.set $b (i32.add (local.get $b) (i32.const 16)))
   (br_if $loop (i32.lt_u (local.get $a) (local.get $end))))
  (i32.const 1))
 (func (export "copyOut") (param $to i32) (param $from i32)
  (memory.copy $pages $live (local.get $to) (local.get $from) (i32.const 65536)))
 (func (export "copyIn") (param $to i32) (param $from i32)
  (memory.copy $live $pages (local.get $to) (local.get $from) (i32.const 65536)))
 (func (export "clear") (param $to i32)
  (memory.fill $live (local.get $to) (i32.const 0) (i32.const 65536)))
 (func (export "copyRange") (param $to i32) (param $from i32) (param $size i32)
  (memory.copy $live $pages (local.get $to) (local.get $from) (local.get $size)))
 (func (export "clearRange") (param $to i32) (param $size i32)
  (memory.fill $live (local.get $to) (i32.const 0) (local.get $size)))
)
