import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const root = new URL('../', import.meta.url);
const sourcePath = 'melee/src/melee/mn/mncharsel.c';
const source = readFileSync(new URL(sourcePath, root), 'utf8');
const kinds = readFileSync(new URL('melee/src/melee/ft/forward.h', root), 'utf8');
const ids = new Map([...kinds.matchAll(/\/\* ([0-9A-F]{2}) \*\/ (CKIND_\w+),/g)].map(m => [m[2], parseInt(m[1], 16)]));
const macros = new Map([...source.matchAll(/^#define (ICON(?:BNDS|ROWHT)_\w+) (.+)$/gm)].map(m => [m[1], m[2]]));
function number(value) {
  const literal = (macros.get(value) ?? value).replace(/[()F]/g, '').trim();
  if (!/^-?\d+(?:\.\d+)?$/.test(literal)) throw new Error(`Unsupported source expression: ${value}`);
  return Number(literal);
}
const table = source.match(/static CSSIcon icons\[25 \+ 1\] = \{([\s\S]*?)\n\};/)?.[1];
if (!table) throw new Error('Melee CSSIcon table not found');
const icons = [...table.replace(/\/\/[^\n]*/g, '').matchAll(/\{([^{}]+)\}/g)].map(m => {
  const fields = m[1].split(',').map(s => s.trim());
  const id = ids.get(fields[1]);
  if (fields.length !== 11 || id === undefined || id > 25) throw new Error('Unexpected CSSIcon structure');
  const [left, right, top, bottom] = fields.slice(7).map(number);
  return { id, left, right, top, bottom };
});
if (icons.length !== 25 || new Set(icons.map(i => i.id)).size !== 25) throw new Error('Expected 25 unique CSS tiles');
const result = `// Generated by scripts/generate-menu.mjs. Do not edit.\n// Original selection bounds, not archive artwork or a running Melee engine.\nexport const menuSource = ${JSON.stringify({ path:sourcePath, sha256:createHash('sha256').update(source).digest('hex') })};\nexport const menuIcons = ${JSON.stringify(icons, null, 2)};\n`;
const target = new URL('web/lib/melee-menu.ts', root);
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== result) throw new Error('Generated menu is stale. Run node scripts/generate-menu.mjs');
  console.log('25 menu tiles match the local Melee source.');
} else {
  writeFileSync(target, result);
  console.log('Generated 25 Melee menu tiles.');
}
