import { readFile, writeFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const source = path.join(root, 'melee/src/melee/ft/kinds');
const prefixes = new Set(['Dr','Mr','Lg','Kp','Pe','Ys','Dk','Ca','Gn','Fc','Fx','Ns','Pp','Nn','Kb','Ss','Zd','Sk','Lk','Cl','Pc','Pk','Pr','Mt','Gw','Ms','Fe']);
const files = new Set(['PlCo.dat','GrNBa.dat']);
async function scan(dir) {
  for (const item of await readdir(dir, {withFileTypes:true})) {
    const file = path.join(dir,item.name);
    if (item.isDirectory()) await scan(file);
    else if (file.endsWith('.c')) {
      for (const match of (await readFile(file,'utf8')).matchAll(/"(Pl([A-Z][a-z])[A-Za-z]*\.dat)"/g)) {
        if (prefixes.has(match[2])) files.add(match[1]);
      }
    }
  }
}
await scan(source);
await writeFile(path.join(root,'web/lib/required-assets.ts'), '// Generated by scripts/generate-assets.mjs from the Melee checkout.\n// Conservative fighter archive inventory; not the complete runtime dependency set.\nexport const requiredAssets = '+JSON.stringify([...files].sort(),null,2)+' as const;\n');
console.log(`Recorded ${files.size} source-referenced fighter/shared/stage archives.`);
